export const RESET_ARRAY = 'RESET_ARRAY';
export const UPDATE_STREAM = 'UPDATE_STREAM';
export const SHOW_ARRAY_OPTIONS = 'SHOW_ARRAY_OPTIONS';
export const CHANGE_LANG_CODE = 'CHANGE_LANG_CODE';
export const UPDATE_LANG = 'UPDATE_LANG';
export const SWAP_STREAM_ORDER = 'SWAP_STREAM_ORDER';
export const UPDATE_LANG_LIST = 'UPDATE_LANG_LIST';